### PR TITLE
Add screenshot mocks

### PR DESCRIPTION
**Pull request by jkmassel**
Updates mocks to work with screenshots (for Android and iOS).

**To Test**
The following PRs must both pass all tests:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/11240/
- https://github.com/wordpress-mobile/WordPress-Android/pull/9928

### CODE REVIEW

**Review by rachelmcr — CHANGES_REQUESTED** [review]
I'm seeing some mocking errors when I run the regular WPiOS UI tests on https://github.com/wordpress-mobile/WordPress-iOS/pull/11240 — the following requests aren't matched:

```
/rest/v1.1/sites/106707880/tags?context=edit&locale=en&order=DESC&order_by=count
/wpcom/v2/sites/106707880/gutenberg?platform=mobile&editor=gutenberg&locale=en
/wp/v2/sites/106707880/media?_locale=user&locale=en
/wp/v2/sites/106707880/media/294?context=edit&_locale=user&locale=en
```

And when I run the WPiOS screenshot tests on that branch I'm seeing errors with these requests not matching:

```
/wp/v2/sites/106707880/media?_locale=user&locale=en
/rest/v1.1/sites/106707880/posts/?locale=en&after=2019-02-01T00%3A00%3A00Z&before=2020-01-15T13%3A13%3A31Z&fields=ID%2C%20title%2C%20URL&number=10
```

Are you seeing the same thing on your end? Let me know if you'd like me to take a closer look at that.

**Comment by jkmassel** [comment]
This is something I'm sort of unclear on in terms of standards for this repo – the UI tests and screenshots all pass with the errors – is it a goal to have zero mocks errors?

I've seen a few cases of [mock errors in other PRs where the tests pass](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/20383), just from drift between the apps and the mocks.

I can see good arguments for both sides tbh, but if we want to be ~lazy~ pragmatic, I think we could say that as long as tests pass, everything is fine. WDYT? Either way, I think we could add it to the PR template for this repo for clarity in the future? :)

**Comment by rachelmcr** [comment]
> This is something I'm sort of unclear on in terms of standards for this repo – the UI tests and screenshots all pass with the errors – is it a goal to have zero mocks errors?

My understanding is that the goal at the outset was zero mocks errors. Any mocks errors on WPAndroid will actually cause the UI tests to fail, and although WPiOS wasn't set up that way I have been working under that assumption on the iOS side as well. (I'm not sure if we could easily update WPiOS to match WPAndroid on this, but that could be one way to make this more clear.)

I see what you mean about being pragmatic but if we allow the mocks errors to compound over time, even if they don't cause failures right away, it could make a real headache for us if we do start to see failures caused by the mocks and have to sift through a bunch of errors to find the problematic one. That said, I'm open to convincing if you think it's not a big deal. Either way, I think updating the PR template makes sense for clarity.

**Review by rachelmcr — APPROVED** [review]
Testing well on both WPiOS and WPAndroid now 👍 Let's merge this!

**Pull request merged**
