### PR TITLE
Fix me/sites stub for Jetpack app screenshots

### PR DESCRIPTION
**Pull request by momo-ozawa**
#### Proposed Changes
This PR fixes the `me/sites` stub for Jetpack app screenshots.

- Updated the Weekend Bakes blog  in the `me/sites` stub to include Jetpack capabilities (i.e. Jetpack specific feature like backup and scan)
- Deleted the custom `me/sites` stub for Jetpack -- we're no longer sending the `filters=jetpack` query param in the Jetpack app, so the custom Jetpack `me/sites` stub is obsolete (ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/17914/commits/23e8f53fe4667b1af09c0addabf33051d4552dd1)

#### To Test

- WordPress iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/18965

cc @wordpress-mobile/platform-9

### CODE REVIEW

**Review by hassaanelgarem — APPROVED** [review]

**Comment by momo-ozawa** [comment]
Hey @mokagio 👋 
Can I go ahead and merge this PR and release `0.0.16`? I know you're going to move WPMocks into the WPiOS repo soon and was wondering if I should wait for that to happen first... thanks! (ref: paNNhX-uk-p2)

**Comment by mokagio** [comment]
@momo-ozawa go for it and thanks for the ping 🙇‍♂️

**Review by AliSoftware — APPROVED** [review]
Didn't check the mock responses thouroughly but explanations make sense and as long as the UI Tests using them in the corresponding WPiOS PR pass, that's enough for me to consider this good to go 🙂

**Comment by mokagio** [comment]
I'm going to take over merging this and its [WordPress iOS counter part](https://github.com/wordpress-mobile/WordPress-iOS/pull/18965) because I want to work on deprecating the repo this week.

**Pull request merged**
